apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simulator-maitri
resources:
  - ../../simulate/k8s/aggregate
patches:
  - path: patches/observation-aggregate-schedule.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: observation-aggregate
