import { requestTitle, requestStation } from '../../services/workloadChanges';
import { isSyntheticDemo, reconcileNow, reviewRequest, setDemoLink, resetSyntheticDemo } from '../../services/syntheticDemo';
import Icon from './Icon';
export default function DemoPanel({ data, refresh, role, onRoleChange }) {
  if (!isSyntheticDemo) return null;
  const approved = (data?.requests || []).filter((r) => ['awaiting-sync', 'delivered'].includes(r.status));
  const queue = approved.filter((r) => r.status === 'awaiting-sync').length;
  return <section className="demo-panel" aria-label="Interactive demo controls">
    <div className="demo-panel-heading"><span className="demo-pill"><Icon name="spark" /> Demo controls</span><button className="quiet-button" onClick={() => { resetSyntheticDemo(); onRoleChange('researcher'); refresh(); }}>Reset demo</button></div>
    <h3>Try a change through a station outage.</h3>
    <p>Pause the link, request a new schedule below, then switch to Station approver to approve or reject it. Restore the link to watch the approved setting become active at the station. Observations keep arriving throughout.</p>
    <div className="demo-role-controls" aria-label="Demo role selection"><span>Experience the demo as</span><div className="station-switch"><button aria-pressed={role === 'researcher'} className={role === 'researcher' ? 'active' : ''} onClick={() => onRoleChange('researcher')}>Researcher</button><button aria-pressed={role === 'approver'} className={role === 'approver' ? 'active' : ''} onClick={() => onRoleChange('approver')}>Station approver</button></div><p>{role === 'researcher' ? 'Can view observations, submit schedule requests, and track outcomes. Cannot approve or reject requests.' : 'Can approve or reject pending requests and speed up delivery of approved changes. Cannot submit schedule requests.'}</p><small>Permissions cover the allowed settings for each station workload.</small></div>
    <div className="demo-steps"><span>1 · Request</span><span>2 · Review</span><span>3 · Queue & deliver</span><span>4 · Station confirms</span></div>
    <div className="demo-link-controls"><button className="quiet-button" aria-pressed={data?.link_up === false} onClick={() => { setDemoLink(!data?.link_up); refresh(); }}>{data?.link_up === false ? 'Restore station link' : 'Simulate link outage'} <Icon name="arrow" /></button><button className="quiet-button" onClick={() => { setDemoLink(!(data?.station_links?.Bharati ?? true), 'Bharati'); refresh(); }}>Bharati: {data?.station_links?.Bharati === false ? 'restore connection' : 'simulate outage'}</button><span>{queue} {queue === 1 ? 'change' : 'changes'} queued · Readings continue every 5 seconds</span></div>
    {approved.length > 0 && <div className="reconcile-panel"><h4>Approved changes</h4><p>Approved changes are applied automatically. An approver can ask the station to apply a change sooner; it still waits for a connection and any earlier changes.</p>{approved.length ? approved.map((request) => <div className="reconcile-row" key={request.request_id}><div><strong>{requestStation(request)} · {requestTitle(request)}</strong><span> {request.status === 'delivered' ? 'Delivered; awaiting confirmation' : 'Queued for delivery'}</span>{request.reconcile_requested_at && <strong>{data?.station_links?.[requestStation(request)] === false && request.status === 'awaiting-sync' ? 'Priority delivery requested · waiting for connection' : 'Priority delivery requested · waiting for confirmation'}</strong>}</div>{role === 'approver' ? <button className="quiet-button" disabled={Boolean(request.reconcile_requested_at)} onClick={() => { reconcileNow(request.request_id, role); refresh(); }}>{request.reconcile_requested_at ? 'Priority requested' : 'Apply sooner'}</button> : <span className="reconcile-permission">Station approver permission required</span>}</div>) : <p className="reconcile-empty">All approved changes have been confirmed.</p>}</div>}
    <details className="infrastructure-details"><summary>How delivery works · Kubernetes & Flux</summary><p>Approved settings become a controlled Git revision. When the connection is available, station-local Git receives the revision and Flux applies it to the authorized workload. “Apply sooner” requests source and workload reconciliation without waiting for the usual polling interval.</p><div className="kubernetes-context"><div><span>Workload</span><code>batch/v1 · CronJob</code><strong>observation-aggregate</strong></div><div><span>Station namespace</span><code>maitri</code><strong>Flux / Kustomize</strong></div><div><span>Applied schedule</span><code>{data?.workload?.applied_schedule || '—'}</code><strong>{data?.workload?.applied_schedule === '0 */6 * * *' ? 'Every 6 hours' : 'Every 12 hours'}</strong></div><div><span>Applied Git revision</span><code>{data?.applied_revision?.slice(0, 12) || '—'}</code><strong>Simulated cluster state</strong></div></div></details>
  </section>;
}
export function DemoReview({ request, refresh, role }) {
  if (!isSyntheticDemo || role !== 'approver' || request.status !== 'pending-approval') return null;
  return <div className="demo-review"><span>Review as station approver</span><button onClick={() => { reviewRequest(request.request_id, true, role); refresh(); }}>Approve change</button><button onClick={() => { reviewRequest(request.request_id, false, role); refresh(); }}>Reject request</button></div>;
}
